### PR TITLE
Support rpm-based distributions

### PR DESCRIPTION
**Pull request by plengauer**

### CODE REVIEW

**Comment by plengauer** [comment]
TODO: sdk shebang causes missing dependency
TODO: _otel_version will not work due to dpkg

**Comment by plengauer** [comment]
TODO: python3-venv does not seem to exist on some rpm based distros, but its implicitly available. maybe python3-venv | dnf

**Comment by plengauer** [comment]
TODO postinst and prerm script will not have parameters, lets default to configure and remove

**Comment by plengauer** [comment]
instead of` dpkf -s` use `dnf info bash | grep Version | cut -d : -f 2 | tr -d ' '`. same will work for yum because its just a redirect to dnf

**Review by moflwi — APPROVED** [review]

**Review by moflwi — APPROVED** [review]

**Review by moflwi — DISMISSED** [review]

**Review by moflwi — APPROVED** [review]

**Pull request merged**
